In [1]:
import trimesh
import numpy as np
#  https://trimesh.org/trimesh.primitives.html#trimesh.primitives.Box.sample_volume
# i guess we can use this to sample points from the mesh 


In [2]:
# load the ply file
mesh = trimesh.load_mesh('example_data/xyzrgb_statuette.ply')

bounds = mesh.bounding_box.bounds


In [15]:
point_we_will_compute = np.array([[-117.973335,-190.473831,-99.822350]])


In [16]:
cl, dist, tri = mesh.nearest.on_surface(point_we_will_compute)

In [17]:
print(f"Closest point: {cl}")
print(f"Distance: {dist}")
print(f"Triangle id: {tri}")


Closest point: [[-101.27983785 -188.94746568  -88.76893051]]
Distance: [20.07936056]
Triangle id: [4763040]


In [18]:
normals = mesh.vertex_normals[mesh.faces[tri]]

print(f"Normal: {normals}")

Normal: [[[-0.8322328  -0.07211909 -0.54971575]
  [-0.86727743 -0.07256815 -0.49250759]
  [-0.8239695  -0.06668347 -0.5626967 ]]]


In [19]:
inside = mesh.contains(point_we_will_compute)
print(f"Is inside: {inside}")

Is inside: [False]


In [20]:
mesh.bounds

array([[-117.97333527, -190.47383118,  -99.82234955],
       [ 117.25061035,  205.56738281,  103.33892059]])

In [11]:
# get the bounding box
bbox = mesh.bounding_box
print(bbox.bounds)

[[-117.97333527 -190.47383118  -99.82234955]
 [ 117.25061035  205.56738281  103.33892059]]
